### ISSUE TITLE
1.18.2 Forge version of the mod consistently crashes on game load.

### ISSUE THREAD

**Issue by Golemosus** [LaidBackSloth42/RainbowLamp#1]
1.18.2 Forge version of the mod consistently crashes on game load. Tested with no other mods loaded. Tested it with rolled back versions of forge (ver. 40.1.68 through to 40.1.73). All logs look the same.
[2022-08-09-7.log.gz](https://github.com/LaidBackSloth42/RainbowLamp/files/9291973/2022-08-09-7.log.gz)

**Comment by LaidBackSloth** [comment]
Fixed as of 1.1
