### ISSUE TITLE
crash error

### ISSUE THREAD

**Issue by cheekymonkey3590** [LaidBackSloth42/RainbowLamp#3]
The game crashed whilst unexpected error
Error: net.minecraftforge.fml.ModLoadingException: Rainbow Lamp (rainbowlamp) encountered an error during the done event phase

i get this when trying to use the latest file.  i use optifine and simonkraft texture back aswell

**Comment by LaidBackSloth** [comment]
Thanks for reporting. Should be fixed in version 1.3.
